// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: message.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	SentTimestamp string                 `protobuf:"bytes,2,opt,name=sent_timestamp,json=sentTimestamp,proto3" json:"sent_timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Data) GetSentTimestamp() string {
	if x != nil {
		return x.SentTimestamp
	}
	return ""
}

type Ack struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Status                string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Payload               []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	OriginalSentTimestamp string                 `protobuf:"bytes,3,opt,name=original_sent_timestamp,json=originalSentTimestamp,proto3" json:"original_sent_timestamp,omitempty"`
	ReceivedTimestamp     string                 `protobuf:"bytes,4,opt,name=received_timestamp,json=receivedTimestamp,proto3" json:"received_timestamp,omitempty"`
	AckSentTimestamp      string                 `protobuf:"bytes,5,opt,name=ack_sent_timestamp,json=ackSentTimestamp,proto3" json:"ack_sent_timestamp,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Ack) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Ack) GetOriginalSentTimestamp() string {
	if x != nil {
		return x.OriginalSentTimestamp
	}
	return ""
}

func (x *Ack) GetReceivedTimestamp() string {
	if x != nil {
		return x.ReceivedTimestamp
	}
	return ""
}

func (x *Ack) GetAckSentTimestamp() string {
	if x != nil {
		return x.AckSentTimestamp
	}
	return ""
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\fping_pong_go\"G\n" +
	"\x04Data\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12%\n" +
	"\x0esent_timestamp\x18\x02 \x01(\tR\rsentTimestamp\"\xcc\x01\n" +
	"\x03Ack\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x126\n" +
	"\x17original_sent_timestamp\x18\x03 \x01(\tR\x15originalSentTimestamp\x12-\n" +
	"\x12received_timestamp\x18\x04 \x01(\tR\x11receivedTimestamp\x12,\n" +
	"\x12ack_sent_timestamp\x18\x05 \x01(\tR\x10ackSentTimestamp2\xb3\x01\n" +
	"\aMessage\x121\n" +
	"\bSendData\x12\x12.ping_pong_go.Data\x1a\x11.ping_pong_go.Ack\x12;\n" +
	"\x12SendDataReceiveAck\x12\x12.ping_pong_go.Data\x1a\x11.ping_pong_go.Ack\x128\n" +
	"\x0fCheckConnection\x12\x12.ping_pong_go.Data\x1a\x11.ping_pong_go.AckB,Z*github.com/etesami/ping-pong-go/pkg/protocb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_proto_goTypes = []any{
	(*Data)(nil), // 0: ping_pong_go.Data
	(*Ack)(nil),  // 1: ping_pong_go.Ack
}
var file_message_proto_depIdxs = []int32{
	0, // 0: ping_pong_go.Message.SendData:input_type -> ping_pong_go.Data
	0, // 1: ping_pong_go.Message.SendDataReceiveAck:input_type -> ping_pong_go.Data
	0, // 2: ping_pong_go.Message.CheckConnection:input_type -> ping_pong_go.Data
	1, // 3: ping_pong_go.Message.SendData:output_type -> ping_pong_go.Ack
	1, // 4: ping_pong_go.Message.SendDataReceiveAck:output_type -> ping_pong_go.Ack
	1, // 5: ping_pong_go.Message.CheckConnection:output_type -> ping_pong_go.Ack
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
