
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-go
      skycluster.io/provider-identifier: os-scinet-zone-2
  template:
    metadata:
      labels:
        app: ping-go
        skycluster.io/app-name: ping-pong
        skycluster.io/managed-by: skycluster
        skycluster.io/provider-identifier: os-scinet-zone-2
    spec:
      containers:
      - name: ping-go
        image: registry.skycluster.io/svc-ping:0.0.6
        imagePullPolicy: Always
        env:
          - name: SVC_ADDR
            value: svc-pong
          - name: SVC_PORT
            value: "50051"
          - name: METRIC_ADDR
            value: 0.0.0.0
          - name: METRIC_PORT
            value: "9100"
          - name: DISABLE_SEND_FILE
            value: "true"
          - name: FILE_SIZE
            value: "0.05"
          - name: UPDATE_FREQUENCY
            value: "10"
      nodeSelector:
        skycluster.io/provider-identifier: os-scinet-zone-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong-go
      skycluster.io/provider-identifier: os-scinet-zone-1
  template:
    metadata:
      labels:
        app: pong-go
        skycluster.io/app-name: ping-pong
        skycluster.io/managed-by: skycluster
        skycluster.io/provider-identifier: os-scinet-zone-1
    spec:
      containers:
      - name: pong-go
        image: registry.skycluster.io/svc-pong:0.0.6
        imagePullPolicy: Always
        env:
          - name: SVC_ADDR
            value: "0.0.0.0"
          - name: SVC_PORT
            value: "50051"
          - name: FILE_SIZE
            value: "0.001"
        ports:
        - containerPort: 50051
          name: pong
      nodeSelector:
        skycluster.io/provider-identifier: os-scinet-zone-1
---
apiVersion: v1
kind: Service
metadata:
  name: svc-pong
  labels:
    skycluster.io/app-name: ping-pong
    skycluster.io/service-type: grpc
    skycluster.io/managed-by: skycluster
spec:
  selector:
    app: pong-go
  ports:
    - name: app
      port: 50051
      targetPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ping-metrics
  labels:
    skycluster.io/app-name: ping-pong
    skycluster.io/service-type: ping
    skycluster.io/managed-by: skycluster
spec:
  selector:
    app: ping-go
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ping-pong-metrics
  namespace: prometheus
spec:
  endpoints:
  - path: /metrics
    port: metrics
    scheme: http
    interval: 10s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      skycluster.io/app-name: ping-pong
      skycluster.io/service-type: ping
      skycluster.io/managed-by: skycluster
